import type { Dependency, LatestVersion, MatrixResult, SecurityFinding } from '../types.js';

type MatrixOptions = {
  dependencies: Dependency[];
  findings: SecurityFinding[];
  latestVersions: LatestVersion[];
  heading: string;
  includeLatestVersion: boolean;
  includeStatusNote: boolean;
  securityStatusAvailable: boolean;
  collapsed?: boolean;
  collapseSummary?: string;
};

const severityOrder: Array<NonNullable<SecurityFinding['severity']>> = [
  'critical',
  'high',
  'medium',
  'low',
];

const severityIcons: Record<NonNullable<SecurityFinding['severity']>, string> = {
  critical: '🔴',
  high: '🔴',
  medium: '🟡',
  low: '🔵',
};

export function generateMatrix(options: MatrixOptions): MatrixResult {
  const findingsByPackage = groupFindings(options.findings);
  const latestByPackage = new Map(
    options.latestVersions.map((latestVersion) => [latestVersion.packageName, latestVersion.version]),
  );
  const headers = ['Dependency', 'Type', 'Current Version'];

  if (options.securityStatusAvailable) headers.push('Security Status');
  if (options.includeLatestVersion) headers.push('Latest npm Version');

  const tableLines = [renderHeader(headers), renderAlignment(headers.length)];

  for (const dependency of options.dependencies) {
    const row = [
      `**${escapeMarkdown(dependency.name)}**`,
      dependency.scope === 'production' ? 'dependencies' : 'devDependencies',
      `\`${dependency.requestedVersion}\``,
    ];

    if (options.securityStatusAvailable) {
      row.push(renderSecurityStatus(findingsByPackage.get(dependency.name) ?? []));
    }

    if (options.includeLatestVersion) {
      row.push(
        renderLatestVersion(dependency.requestedVersion, latestByPackage.get(dependency.name)),
      );
    }

    tableLines.push(renderRow(row));
  }

  const lines = ['', options.heading, ''];

  const tag = options.collapsed ? '<details>' : '<details open>';
  const defaultSummary = options.collapsed ? 'Click to expand' : 'Click to collapse / expand';
  const summary = `${options.collapseSummary?.trim() || defaultSummary} (${renderInsights(options, latestByPackage)})`;

  lines.push(tag, `<summary>${summary}</summary>`, '', ...tableLines, '', '</details>');

  if (!options.securityStatusAvailable && options.includeStatusNote) {
    lines.push('', '> Security status unavailable because no scanner report was provided or parsed.');
  }

  lines.push('', '*Table generated by [dependency-security-matrix-action](https://github.com/roman-pinchuk/dependency-security-matrix-action).*', '');

  return {
    markdown: `${lines.join('\n')}\n`,
    dependencyCount: options.dependencies.length,
    latestVersionCount: options.latestVersions.filter((latestVersion) => latestVersion.version).length,
    issueCount: options.findings.length,
    securityStatusAvailable: options.securityStatusAvailable,
  };
}

function groupFindings(findings: SecurityFinding[]): Map<string, SecurityFinding[]> {
  const grouped = new Map<string, SecurityFinding[]>();

  for (const finding of findings) {
    const existing = grouped.get(finding.packageName) ?? [];
    existing.push(finding);
    grouped.set(finding.packageName, existing);
  }

  return grouped;
}

function renderHeader(headers: string[]): string {
  return renderRow(headers);
}

function renderAlignment(columnCount: number): string {
  return renderRow(Array.from({ length: columnCount }, () => ':---'));
}

function renderRow(cells: string[]): string {
  return `| ${cells.join(' | ')} |`;
}

function renderSecurityStatus(findings: SecurityFinding[]): string {
  if (findings.length === 0) return '🟢 No known issues';

  const severityCounts = severityOrder
    .map((severity) => {
      const count = findings.filter((finding) => finding.severity === severity).length;
      const icon = severityIcons[severity];
      return count > 0 ? `${icon} ${count} ${severity}` : undefined;
    })
    .filter(Boolean);

  if (severityCounts.length === 0) return `⚠️ ${findings.length} issue${findings.length === 1 ? '' : 's'}`;

  return severityCounts.join(', ');
}

function renderInsights(
  options: MatrixOptions,
  latestByPackage: Map<string, string | undefined>,
): string {
  const insights: string[] = [];

  if (options.includeLatestVersion) {
    const outdatedCount = options.dependencies.filter((dependency) => {
      const latestVersion = latestByPackage.get(dependency.name);
      return latestVersion ? isOutdated(dependency.requestedVersion, latestVersion) : false;
    }).length;

    insights.push(`${outdatedCount} outdated`);
  }

  if (!options.securityStatusAvailable) {
    insights.push('security unavailable');
  } else if (options.findings.length === 0) {
    insights.push('no known vulnerabilities');
  } else {
    const severityCounts = severityOrder
      .map((severity) => {
        const count = options.findings.filter((finding) => finding.severity === severity).length;
        return count > 0 ? `${count} ${severity}` : undefined;
      })
      .filter((count): count is string => count !== undefined);
    const unspecifiedCount = options.findings.filter((finding) => !finding.severity).length;

    if (unspecifiedCount > 0) severityCounts.push(`${unspecifiedCount} unspecified`);
    insights.push(
      `${options.findings.length} ${options.findings.length === 1 ? 'vulnerability' : 'vulnerabilities'}: ${severityCounts.join(', ')}`,
    );
  }

  return insights.join(', ');
}

function parseSemver(v: string): [number, number, number] | null {
  const match = v.match(/(\d+)\.(\d+)(?:\.(\d+))?/);
  if (!match || !match[1] || !match[2]) return null;
  return [parseInt(match[1], 10), parseInt(match[2], 10), parseInt(match[3] ?? '0', 10)];
}

function isOutdated(requestedVersion: string, latestVersion: string): boolean {
  const req = parseSemver(requestedVersion);
  const lat = parseSemver(latestVersion);
  if (!req || !lat) return false;

  if (lat[0] > req[0]) return true;
  if (lat[0] < req[0]) return false;

  if (lat[1] > req[1]) return true;
  if (lat[1] < req[1]) return false;

  return lat[2] > req[2];
}

function renderLatestVersion(requestedVersion: string, latestVersion: string | undefined): string {
  if (!latestVersion) return 'Unavailable';

  if (isOutdated(requestedVersion, latestVersion)) {
    return `\`${latestVersion}\` ⚠️`;
  }
  return `\`${latestVersion}\``;
}

function escapeMarkdown(value: string): string {
  return value.replace(/\|/g, '\\|');
}
